### ISSUE TITLE
VRC Update

### ISSUE THREAD

**Issue by Dervali-git** [RequiDev/FBTSaver#4]
VRC updated, this is now "VRCTrackingSteam.Method_Public_Virtual_Boolean_String_3"

https://github.com/RequiDev/FBTSaver/blob/163aff2b5ce5c076caef1029648145d94bdd4921/FBT%20Saver/FBTSaver.cs#L24

**Comment by RequiDev** [comment]
Thanks!
https://github.com/RequiDev/FBTSaver/releases/tag/v1.0.7
