### ISSUE TITLE
VRC Update 

### ISSUE THREAD

**Issue by Dervali-git** [RequiDev/FBTSaver#5]
Updated again, thankfully only this variable changed, it is back to 'VRCTrackingSteam.Method_Public_Virtual_Boolean_String_0'

https://github.com/RequiDev/FBTSaver/blob/163aff2b5ce5c076caef1029648145d94bdd4921/FBT%20Saver/FBTSaver.cs#L24

Hope this saves you a couple minutes of time!

**Comment by RequiDev** [comment]
Fixed in 5572170fc2793f6a3bc9ae20b3dd489d55d617c3
